/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package onlinereservation;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kailas
 */
public class addtrain extends javax.swing.JFrame {

    /**
     * Creates new form addtrain
     */
    public addtrain() {
        initComponents();   
        connect();
        Train_Details();
    }
    
    
    Connection con;
    PreparedStatement pst;
     ResultSet rs;
    
    
    
      public void connect() 
                
      {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/reservation","root","");
            } catch (SQLException ex) {
                Logger.getLogger(addtrain.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addtrain.class.getName()).log(Level.SEVERE, null, ex);
        }
       
      
      }
     public void Train_Details()
              
      {
      
        try {
            pst = con.prepareStatement("select * from details ");
            rs = pst.executeQuery();
            
             ResultSetMetaData rsd = (ResultSetMetaData) rs.getMetaData();
            int c;
            c = rsd.getColumnCount();
             DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            
            while(rs.next())
             {
                 Vector v = new Vector(); 
                for(int i=0; i<=c; i++)
         {
         
             v.add(rs.getString("tno"));
             v.add(rs.getString("tname"));
             v.add(rs.getString("StartPlace"));
             v.add(rs.getString("destinationplace"));
             v.add(rs.getString("class"));            
             v.add(rs.getString("Departs"));
             v.add(rs.getString("Arrives"));
             v.add(rs.getString("price"));
         
         }
             d.addRow(v);
                 
           }

            
        } catch (SQLException ex) {
            Logger.getLogger(addtrain.class.getName()).log(Level.SEVERE, null, ex);
        }
          
          
      }
      
            /**
             * This method is called from within the constructor to initialize the form.
             * WARNING: Do NOT modify this code. The content of this method is always
             * regenerated by the Form Editor.
             */
            @SuppressWarnings("unchecked")
            // <editor-fold defaultstate="collapsed" desc="Generated Code">
            
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tstartplace = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tdplace = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdeptime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtarrtime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtclass = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Train");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 175, 36));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add train");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 426, 93, 43));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 426, 93, 43));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 426, 93, 43));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train No", "Train Name", "startplace", "Destinationplace", "Class", "Departs", "Arrives", "price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Train No:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel1.add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 196, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Train Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        jPanel1.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 196, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("StartPlace:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(tstartplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 196, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DestinationPlace:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        tdplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdplaceActionPerformed(evt);
            }
        });
        jPanel1.add(tdplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 193, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Departs:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel1.add(txtdeptime, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 193, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Arrives:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));
        jPanel1.add(txtarrtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 193, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Price:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        jPanel1.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 196, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 93, 43));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Class :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 60, -1));
        jPanel1.add(txtclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 193, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 93, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kailas\\Desktop\\train images\\train7.jpg")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 530));

        setSize(new java.awt.Dimension(827, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       String tno = txtno.getText();
       String trainname =tname.getText();
       String splace = tstartplace.getText();
       String dplace =tdplace.getText();
       String Class =txtclass.getText();      
       String dtime =txtdeptime.getText();
       String arrtime =txtarrtime.getText();
       String price =txtprice.getText();
       
       
        try {
            pst= con.prepareStatement("insert into details(tno,tname,startPlace,destinationplace,class,Departs,Arrives,price)values(?,?,?,?,?,?,?,?)");
        
            pst.setString(1, tno);
            pst.setString(2, trainname);
            pst.setString(3,splace );
            pst.setString(4,dplace );
            pst.setString(5,Class );
            pst.setString(6,dtime );
            pst.setString(7,arrtime );
            pst.setString(8,price );
            int k =pst.executeUpdate();
            
             if(k==1)
            {
                JOptionPane.showMessageDialog(this,"Record Adddedddd");
            }
            else
            {
             JOptionPane.showMessageDialog(this,"Record failed");
             
            }
            
           txtno.setText("");
           tname.setText("");
           tstartplace.setText("");
            tdplace.setText("");
            txtclass.setText("");
            txtdeptime.setText("");
            txtarrtime.setText("");
            txtprice.setText("");
            txtno.requestFocus();
             Train_Details();
              
        } catch (SQLException ex) {
            Logger.getLogger(addtrain.class.getName()).log(Level.SEVERE, null, ex);
        }
       
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
          int selectIndex = jTable1.getSelectedRow();
        
          txtno.setText(d.getValueAt(selectIndex, 0).toString());
          tname.setText(d.getValueAt(selectIndex, 1).toString());
          tstartplace.setText(d.getValueAt(selectIndex, 2).toString());
          tdplace.setText(d.getValueAt(selectIndex, 3).toString());
          txtclass.setText(d.getValueAt(selectIndex, 4).toString());
          txtdeptime.setText(d.getValueAt(selectIndex, 5).toString());
          txtarrtime.setText(d.getValueAt(selectIndex, 6).toString());        
          txtprice.setText(d.getValueAt(selectIndex, 7).toString());
        
          jButton1.setEnabled(false);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       String tno = txtno.getText();
       String trainname =tname.getText();
       String splace = tstartplace.getText();
       String dplace  =tdplace.getText();
       String Class  =txtclass.getText();
       String dtime =txtdeptime.getText();
       String arrtime =txtarrtime.getText();
       String price =txtprice.getText();
       
       
        try {
            pst= con.prepareStatement("update  details set tname = ?,StartPlace = ?,destinationplace = ?,Class = ?,Departs = ?,Arrives = ?,price= ? where tno=? ");
        
            pst.setString(1,trainname );
            pst.setString(2,splace );
            pst.setString(3,dplace );
            pst.setString(4,Class );
            pst.setString(5,dtime );
            pst.setString(6,arrtime );
            pst.setString(7,price );
            pst.setString(8,tno );
            int k =pst.executeUpdate();
            
             if(k==1)
            {
                JOptionPane.showMessageDialog(this,"Record UPDATEDDDD");
            }
            else
            {
             JOptionPane.showMessageDialog(this,"Record failed");
             
            }
            
           txtno.setText("");
           tname.setText("");
           tstartplace.setText("");
            tdplace.setText("");
            txtclass.setText("");
            txtdeptime.setText("");
            txtarrtime.setText("");
            txtprice.setText("");
            txtno.requestFocus();
            
             Train_Details();
             jButton1.setEnabled(true);
             
        } catch (SQLException ex) {
            Logger.getLogger(addtrain.class.getName()).log(Level.SEVERE, null, ex);
        }
       
              
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        
         String tno = txtno.getText();
       
       
       
        try {
            pst= con.prepareStatement(" delete from details where tno=? ");
        
            pst.setString(1,tno );
           
            int k =pst.executeUpdate();
            
             if(k==1)
            {
                JOptionPane.showMessageDialog(this,"Record Deletedd");
            }
            else
            {
             JOptionPane.showMessageDialog(this,"Record failed");
             
            }
            
           txtno.setText("");
           tname.setText("");
           tstartplace.setText("");
            tdplace.setText("");
            txtclass.setText("");
            txtdeptime.setText("");
            txtarrtime.setText("");
            txtprice.setText("");
            txtno.requestFocus();
            
             Train_Details();
             jButton1.setEnabled(true);
             
        } catch (SQLException ex) {
            Logger.getLogger(addtrain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         Train_Details();
            jButton1.setEnabled(true);
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tdplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdplaceActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
         reservation re = new  reservation ();
         re.show();
         dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addtrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addtrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addtrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addtrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addtrain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tdplace;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tstartplace;
    private javax.swing.JTextField txtarrtime;
    private javax.swing.JTextField txtclass;
    private javax.swing.JTextField txtdeptime;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
